cp	/usr/local/lib/libvtkFiltersFlowPaths-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersGeneric-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersHyperTree-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersParallelImaging-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersPoints-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersProgrammable-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersSMP-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersSelection-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersTopology-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersVerdict-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkGUISupportQtOpenGL-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkGUISupportQtSQL-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkGeovisCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOAMR-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOEnSight-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOExodus-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOExportOpenGL2-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOImport-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOInfovis-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOLSDyna-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOMINC-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOMovie-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOPLY-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOParallel-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOParallelXML-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOTecplotTable-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOVideo-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingMorphological-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingStatistics-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingStencil-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkInteractionImage-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingContextOpenGL2-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingImage-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingLOD-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingQt-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingVolumeOpenGL2-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkViewsContext2D-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkViewsQt-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkDomainsChemistry-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkverdict-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOSQL-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtksqlite-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkproj4-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersAMR-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOExport-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingGL2PSOpenGL2-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkgl2ps-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtklibharu-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtklibxml2-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkoggtheora-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersParallel-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkexoIIc-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOGeometry-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIONetCDF-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtknetcdfcpp-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkNetCDF-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkhdf5_hl-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkhdf5-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/lib/libSystem.B.dylib    ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkjsoncpp-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkParallelCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOLegacy-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersTexture-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingMath-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkGUISupportQt-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingOpenGL2-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkglew-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa    ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkViewsInfovis-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkChartsCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingContext2D-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersImaging-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkInfovisLayout-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkInfovisCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkViewsCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkInteractionWidgets-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersHybrid-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingGeneral-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingSources-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersModeling-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkInteractionStyle-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersExtraction-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersStatistics-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingFourier-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkalglib-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingHybrid-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOImage-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkDICOMParser-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkmetaio-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkpng-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtktiff-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkjpeg-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingAnnotation-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingColor-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingVolume-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkImagingCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOXML-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOXMLParser-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkIOCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtklz4-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkexpat-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingLabel-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingFreeType-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkRenderingCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonColor-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersGeometry-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersSources-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersGeneral-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonComputationalGeometry-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkFiltersCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonExecutionModel-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonDataModel-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonMisc-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonSystem-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtksys-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonTransforms-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonMath-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkCommonCore-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkfreetype-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
cp	/usr/local/lib/libvtkzlib-8.1.1.dylib     ./stlViewer.app/Contents/Frameworks
